// This is a map that allows any incorrect spellings/instances of program names to match the proper name of the department. 
//

export const CORRECT_PROGRAM_NAMES = {
    "Mechanical Eng Tech": "Mechanical Engineering Tech",
    "Manufctring Eng Tech": "Manufacturing Engineering Technology",
    "Master of Science in Comp Engr": "Computer Engineering",
    "Design Engr Tech": "Product Design and Development",
    "Electrical Engrng": "Electrical Engineering",
    "Network MGMT Tech": "Network Management Tech",
    "Automotive Svc Tech": "Automotive Service Tech",
    "Construction Mgmt Tech": "Construction Management Tech",
    "Interior Design Tech": "Interior Design",
    "Sales & Merchandising": "Sales and Merchandising",
    "Pre-Engineering": "Pre Engineering",
    "Electronic Engnr Tec": "Electrical Engineering",
    "Manufactring Eng Tech": "Manufacturing Engineering Technology",
    "Electronics Engnr Tec": "Electrical Engineering",
    "Customized Option": "Customized CS",
    "Web and User Experience": "Web Development : User Experience & Design Concentration",
    "Web & User Experience, User Experience Design": "Web Development : User Experience & Design Concentration",
    "Construction Mgmt Tec": "Construction Management Tech",
    "Systms Engr & Sustainable Engr": "Systems Engineering and Sustainable Engineering",
    "User Experience Design": "User Experience and Design",
    "Apprenticeship": "Construction Apprenticeship",
    "Building Design & Construction": "Building and Design Construction",
    "Building Design & Const": "Building and Design Construction",
    "Network Technologies": "Network Management Tech",
    "Design Engineering Technology": "Product Design and Development",
    "Product Design & Development": "Product Design and Development",
    "Systms Engr & Sustainable Engr": "Systems Engineering and Sustainable Engineering",
    "Design Grphcs Eng Tech": "Design Graphics Engineering Tech",
    "Manufact/Welding Engr Tech": "MFET: Welding Emphasis",
    "Independnt Shop ATEP": "Independent Shop",
    "Automotive Svc Tech": "Automotive Service Tech",
    "General Motors ASEP": "Automotive Tech",
    "Adv Vehicle Systems": "Advanced Vehicle Systems",
    "Field Service Ops": "Field Service Operations",
    "Technical Sales": "Professional Sales",
    "Automotive Service Technology": "Automotive Service Tech",
    "Automotive & Vehicle Engineering Technology": "Automotive and Vehicle Engineering Tech",

}